/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import * as THREE from 'three';

import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../constants/theme';
import { computeBoundsTree, disposeBoundsTree, acceleratedRaycast } from 'three-mesh-bvh';

// Extend THREE only once
if (!THREE.BufferGeometry.prototype.computeBoundsTree) {
  THREE.BufferGeometry.prototype.computeBoundsTree = computeBoundsTree;
  THREE.BufferGeometry.prototype.disposeBoundsTree = disposeBoundsTree;
  THREE.Mesh.prototype.raycast = acceleratedRaycast;
}

export function TrackCurvedLeft({ isGhost, isOccupied, isSnapped, isSelected, ...props }) {
  const { nodes, materials } = useGLTF('/models/track_curved_L-opt.glb')

  useEffect(() => {
      const geo = nodes.straight.geometry;
      geo.computeBoundsTree();
      return () => geo.disposeBoundsTree();
    }, [nodes]);

  const getMaterialColor = () => {
    if (isOccupied) return interactionColor.occupied;
    if (isSnapped) return interactionColor.snap;  
    if (isSelected) return interactionColor.selected;
    return interactionColor.default;                 
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        name="track_curved-l"
        castShadow
        receiveShadow
        geometry={nodes['track_curved-l'].geometry}
        material={nodes['track_curved-l'].material}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/track_curved_L-opt.glb')
