/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../constants/theme';


export const TrackYSwitch = forwardRef(({ isGhost, raycast, isOccupied, isSnapped, isSelected, ...props }, ref) => {
  const { nodes, materials } = useGLTF('/models/track_switch-opt.glb')

  useEffect(() => {
      if (nodes.Y) {
        const geo = nodes.Y.geometry;
        if (!geo.boundsTree) geo.computeBoundsTree();
        if (!geo.boundingBox) geo.computeBoundingBox();
      }
    }, [nodes]);

  const getMaterialColor = () => {
      if (isOccupied) return interactionColor.occupied;
      if (isSnapped) return interactionColor.snap; 
      if (isSelected) return interactionColor.selected; 
      return interactionColor.default;                 
    }
    
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        raycast={raycast}
        name="Y"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.Y.geometry}
        material={nodes.Y.material}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
      <mesh
        raycast={raycast}
        name="switch"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes['switch'].geometry}
        material={materials['Material.001']}
      >
        {isGhost && (
          <meshStandardMaterial 
            map={materials['Material.001'].map} 
            transparent={true} 
            opacity={0.5} 
          />
        )}
      </mesh>
    </group>
  )
})

useGLTF.preload('/models/track_switch-opt.glb')
