/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../constants/theme';

export const TrackCross90 = forwardRef(({ isGhost, raycast, isOccupied, isSnapped, isSelected, ...props }, ref) =>{
  const { nodes, materials } = useGLTF('/models/track_cross90-opt.glb')

  useEffect(() => {
      if (nodes.cross90) {
        const geo = nodes.cross90.geometry;
        if (!geo.boundsTree) geo.computeBoundsTree();
        if (!geo.boundingBox) geo.computeBoundingBox();
      }
    }, [nodes]);

  const getMaterialColor = () => {
      if (isOccupied) return interactionColor.occupied;
      if (isSnapped) return interactionColor.snap;  
      if (isSelected) return interactionColor.selected;
      return interactionColor.default;                 
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        raycast={raycast}
        name="cross90"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.cross90.geometry}
        material={nodes.cross90.material}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
})

useGLTF.preload('/models/track_cross90-opt.glb')
