/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useEffect } from 'react';
import * as THREE from 'three';
import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../constants/theme';
import { computeBoundsTree, disposeBoundsTree, acceleratedRaycast } from 'three-mesh-bvh';

// Extend THREE only once
if (!THREE.BufferGeometry.prototype.computeBoundsTree) {
  THREE.BufferGeometry.prototype.computeBoundsTree = computeBoundsTree;
  THREE.BufferGeometry.prototype.disposeBoundsTree = disposeBoundsTree;
  THREE.Mesh.prototype.raycast = acceleratedRaycast;
}

export const TrackCurved = forwardRef(({ isGhost, isOccupied, isSnapped, isSelected, raycast, ...props }, ref) => {
  const { nodes, materials } = useGLTF('/models/track_curved-opt.glb')

  useEffect(() => {
      const geo = nodes.straight.geometry;
      geo.computeBoundsTree();
      return () => geo.disposeBoundsTree();
    }, [nodes]);

  const getMaterialColor = () => {
    if (isOccupied) return interactionColor.occupied;
    if (isSnapped) return interactionColor.snap;  
    if (isSelected) return interactionColor.selected;
    return interactionColor.default;                 
  }
  
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        name="curved_track"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.track_curved.geometry}
        material={nodes.track_curved.material}
        raycast={raycast}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
})

useGLTF.preload('/models/track_curved-opt.glb')
