/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TrackStraight({ isGhost, isOccupied, isSnapped, ...props }) {
  const { nodes, materials } = useGLTF('/models/track_straight-transformed.glb')

  // Plastic logic
  const getMaterialColor = () => {
    if (isOccupied) return '#ff4444'; // Red
    if (isSnapped) return '#44ff44';  // Green
    return '#8a8a8a';                 // Duplo Grey
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        name="straight"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.straight.geometry}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/track_straight-transformed.glb')
