/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../constants/theme';

export const TrackCurvedLeft = forwardRef(({ isGhost, raycast, isOccupied, isSnapped, isSelected, ...props }, ref) => {
  const { nodes, materials } = useGLTF('/models/track_curved_L-opt.glb')

  useEffect(() => {
      if (nodes['track_curved-l']) {
        const geo = nodes['track_curved-l'].geometry;
        if (!geo.boundsTree) geo.computeBoundsTree();
        if (!geo.boundingBox) geo.computeBoundingBox();
      }
    }, [nodes]);
    
  const getMaterialColor = () => {
    if (isOccupied) return interactionColor.occupied;
    if (isSnapped) return interactionColor.snap;  
    if (isSelected) return interactionColor.selected;
    return interactionColor.default;                 
  }

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={ref}
        name="track_curved-l"
        castShadow
        receiveShadow
        geometry={nodes['track_curved-l'].geometry}
        material={nodes['track_curved-l'].material}
        raycast={raycast}

      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
    </group>
  )
})

useGLTF.preload('/models/track_curved_L-opt.glb')
