/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import * as THREE from 'three';

import { useGLTF } from '@react-three/drei'
import { interactionColor } from '../../constants/theme';
import { computeBoundsTree, disposeBoundsTree, acceleratedRaycast } from 'three-mesh-bvh';

// Extend THREE only once
if (!THREE.BufferGeometry.prototype.computeBoundsTree) {
  THREE.BufferGeometry.prototype.computeBoundsTree = computeBoundsTree;
  THREE.BufferGeometry.prototype.disposeBoundsTree = disposeBoundsTree;
  THREE.Mesh.prototype.raycast = acceleratedRaycast;
}

export function TrackYSwitch({ isGhost, isOccupied, isSnapped, isSelected, ...props }) {
  const { nodes, materials } = useGLTF('/models/track_switch-opt.glb')

  useEffect(() => {
      const geo = nodes.straight.geometry;
      geo.computeBoundsTree();
      return () => geo.disposeBoundsTree();
    }, [nodes]);

  const getMaterialColor = () => {
      if (isOccupied) return interactionColor.occupied;
      if (isSnapped) return interactionColor.snap; 
      if (isSelected) return interactionColor.selected; 
      return interactionColor.default;                 
    }
    
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Y"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes.Y.geometry}
        material={nodes.Y.material}
      >
        <meshStandardMaterial 
          color={getMaterialColor()}
          roughness={0.4}   // Smooth plastic reflection
          metalness={0.0}   // Non-metallic
          transparent={isGhost}
          opacity={isGhost ? 0.5 : 1}
        />
      </mesh>
      <mesh
        name="switch"
        castShadow={true}
        receiveShadow={true}
        geometry={nodes['switch'].geometry}
        material={materials['Material.001']}
      >
        {isGhost && (
          <meshStandardMaterial 
            map={materials['Material.001'].map} 
            transparent={true} 
            opacity={0.5} 
          />
        )}
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/track_switch-opt.glb')
